export const TOGGLE_MENU = 'TOGGLE_MENU';
export const ADD_USER = 'ADD_USER';
export const FETCH_PERSON_BEGIN = 'FETCH_PERSON_BEGIN';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';
